import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ProjectActivity = () => {
    const activities = [
        { id: 'c1', ref: 'OPS-822', message: 'Manual roof dismantling complete', site: 'Lavington Mansion', time: '2h ago', status: 'verified' },
        { id: 'c2', ref: 'OPS-394', message: 'Crystal chandelier recovery initiated', site: 'Runda Heights', time: '5h ago', status: 'active' },
        { id: 'c3', ref: 'OPS-107', message: 'Rebar mesh structural audit uploaded', site: 'Industrial Area', time: '1d ago', status: 'verified' },
        { id: 'c4', ref: 'OPS-955', message: 'Initial site clearance sequence started', site: 'Karen Estate', time: '2d ago', status: 'scheduled' },
    ];
    const projects = [
        { name: 'Site-Lavington-Phase1', salvage: '98%', status: 'Complete', color: 'bg-green-500' },
        { name: 'Site-Runda-Interior', salvage: '45%', status: 'In Progress', color: 'bg-blue-500' },
        { name: 'Site-Karen-Foundation', salvage: '12%', status: 'Pending', color: 'bg-yellow-500' }
    ];
    return (_jsx("section", { id: "activity", className: "py-24 bg-slate-950 text-slate-300 font-sans", children: _jsx("div", { className: "container mx-auto px-6", children: _jsxs("div", { className: "flex flex-col lg:flex-row gap-12", children: [_jsxs("div", { className: "lg:w-2/3", children: [_jsxs("div", { className: "flex items-center justify-between mb-8 border-b border-slate-800 pb-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("i", { className: "fas fa-tower-broadcast text-3xl text-white" }), _jsx("h2", { className: "text-2xl font-bold text-white tracking-tight", children: "Live Operations Pulse" })] }), _jsxs("div", { className: "hidden sm:flex space-x-2", children: [_jsx("span", { className: "px-3 py-1 rounded-md bg-slate-800 text-[10px] font-mono", children: "CHANNEL: HQ-LIVE" }), _jsx("span", { className: "px-3 py-1 rounded-md bg-blue-500/10 text-blue-400 text-[10px] font-mono border border-blue-500/20", children: "REAL-TIME DATA" })] })] }), _jsx("div", { className: "space-y-4", children: activities.map((activity) => (_jsxs("div", { className: "group flex items-start space-x-4 p-4 rounded-xl hover:bg-slate-900 transition-colors border border-transparent hover:border-slate-800", children: [_jsx("div", { className: `mt-1 w-8 h-8 rounded-full flex items-center justify-center ${activity.status === 'verified' ? 'bg-purple-500/20 text-purple-400' :
                                                activity.status === 'active' ? 'bg-green-500/20 text-green-400' : 'bg-slate-700/20 text-slate-400'}`, children: _jsx("i", { className: `fas ${activity.status === 'verified' ? 'fa-circle-check' : 'fa-circle-dot'} text-sm` }) }), _jsxs("div", { className: "flex-grow", children: [_jsxs("div", { className: "flex items-center space-x-2 mb-1", children: [_jsx("span", { className: "text-sm font-bold text-white group-hover:text-blue-400 transition-colors cursor-pointer", children: activity.message }), _jsx("span", { className: "text-[10px] font-mono text-slate-500 bg-slate-800 px-2 py-0.5 rounded", children: activity.ref })] }), _jsxs("div", { className: "flex items-center space-x-3 text-xs text-slate-500", children: [_jsxs("span", { className: "flex items-center", children: [_jsx("i", { className: "fas fa-map-marker-alt mr-1.5" }), " ", activity.site] }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: activity.time })] })] }), _jsx("div", { className: "hidden sm:block", children: _jsx("span", { className: `text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded border ${activity.status === 'verified' ? 'border-purple-500/30 text-purple-400' :
                                                    activity.status === 'active' ? 'border-green-500/30 text-green-400' : 'border-slate-700 text-slate-500'}`, children: activity.status }) })] }, activity.id))) }), _jsx("div", { className: "mt-8", children: _jsx("button", { className: "w-full py-3 bg-slate-900 border border-slate-800 rounded-xl text-sm font-bold hover:bg-slate-800 transition text-slate-400", children: "View Full Operational History" }) })] }), _jsxs("div", { className: "lg:w-1/3", children: [_jsx("h3", { className: "text-sm font-bold uppercase tracking-widest text-slate-500 mb-6", children: "Ongoing Site Operations" }), _jsx("div", { className: "space-y-4", children: projects.map((project) => (_jsxs("div", { className: "p-5 rounded-2xl bg-slate-900/50 border border-slate-800 hover:border-blue-500/30 transition-all", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("i", { className: "fas fa-building-circle-check text-blue-400" }), _jsx("span", { className: "font-bold text-slate-200 text-sm", children: project.name })] }), _jsx("div", { className: `w-2 h-2 rounded-full ${project.color} animate-pulse` })] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] text-slate-500", children: [_jsxs("div", { className: "flex space-x-4", children: [_jsxs("span", { className: "flex items-center", children: [_jsx("i", { className: "fas fa-gem text-blue-400/50 mr-1" }), " ", project.salvage, " Recovery"] }), _jsxs("span", { className: "flex items-center", children: [_jsx("i", { className: "fas fa-users mr-1" }), " Site Team"] })] }), _jsx("span", { className: "text-slate-400", children: project.status })] })] }, project.name))) }), _jsxs("div", { className: "mt-8 p-6 rounded-2xl bg-blue-600/10 border border-blue-500/20", children: [_jsx("h4", { className: "font-bold text-white mb-2", children: "Partner With Us?" }), _jsx("p", { className: "text-xs text-slate-400 leading-relaxed mb-4", children: "Our methodology is optimized for safety and efficiency. Inquire about our proprietary manual dismantling standards." }), _jsx("a", { href: "https://wa.me/254700192081", className: "text-blue-400 text-xs font-bold hover:underline", children: "Request technical documentation \u2192" })] })] })] }) }) }));
};
export default ProjectActivity;
